import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Main } from "./components/Main";
import { Sidebar } from "./components/Sidebar";
import songs from "./lib/songs";
import Player from "./components/Player";

export const metadata = {
  title: "Spotify - Web Clone: Music for everyone",
  description: "Generated by { uIuski, medev2e }",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-screen bg-black">
          <Navbar />
          <div className="flex h-screen p-2 gap-2 bg-black overflow-hidden">
            <Sidebar />
            <Main songs={songs} />
          </div>
          <Player />
        </div>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
